### ISSUE TITLE
Example (Current) "hello world" usage of this library / libjsqlite?

### ISSUE THREAD

**Issue by kristina-hager** [geopaparazzi/libjsqlite-spatialite-android#12] opened 2015-09-03 01:57 UTC
Hi there, I'm hoping to use spatialite on android for a [school project](https://fahrradlercode.wordpress.com/2015/08/25/an-about-face-on-my-project-time-to-save-salamanders-with-gis/). I have some experience developing android apps. However, I've never used this sort of library before in android.

Do you know of any recent, simple, android app using these libraries? I've been digging through the geopaparazzi app source/structure lately, but I am not having luck imitating that apps setup since it is so complex. I've found some simpler examples such as [android-spatialite](https://github.com/mrenouf/android-spatialite), but those are using a very old spatialite version and also an old Android development environment.

Most online articlces indicate that to use an 'android library' you should have some *.jar or *.aar file. I've not managed to find such a thing for as recent spatialite/android as is here. I have tried just adding the 'libjsqlite.so' directly to an app with no luck. Lately, I am trying to use the libjsqlite.so and the SQLite java sources to create an android module, also with no luck.

Or do you have any tips on how to set up a hello world example with these libs? Btw, I am perfectly willing to take on the effort to create such a hello world example to go with these libs and make it open source of course. However, I could just use some help [getting started](http://stackoverflow.com/questions/32290214/call-function-from-a-shared-lib-in-an-android-application).

**Comment by mj10777** [comment] 2015-09-03 04:34
>> Do you know of any recent, simple, android app using these libraries?
* no, although there are many that report using it
   * but I have seen no results

---
>> I've been digging through the geopaparazzi app source/structure lately, but I am not having luck imitating that apps setup since it is so complex.
* very true

One of the major goals 2 (or 3) years ago was get
* `geopaparazzispatialitelibrary`
to be completely independent of the other library and the main application.

This is about 85% complete, but there are still portions referencing other library's
* `eu.geopaparazzi.library` being the main one

The worst problem is however the dependency of the actual painting of the geometry results
* `geopaparazzi.app/src/eu/hydrologis/geopaparazzi/maps/overlays/GeopaparazziOverlay.java`
   * `drawFromSpatialite()` and other function that it calls
      * `stopDrawing()`
      * `drawGeometry()`
      * `drawLabel()`

If these were spitted into a 
* `SpatialiteOverlay.java`
and included into `geopaparazzispatialitelibrary`

The in the application 
* `geopaparazzi/maps/MapsActivity.java`
    * `onResume()`

```
        dataOverlay = new ArrayGeopaparazziOverlay(this);
        List<Overlay> overlays = mapView.getOverlays();
        overlays.clear();
        overlays.add(dataOverlay);
```
could be adapted to add a second overlay, something in the form of:

```
SpatialiteOverlay geomOverlay=new SpatialiteOverlay;
overlays.add(geomOverlay);
``` 
This would be a *default* painting of the geometries offered by `geopaparazzispatialitelibrary`
* that could be overridden by any application as needed

With this `geopaparazzispatialitelibrary` would be a good 90% self contained, which was the main goal
* then being simple included in another project

---
In a nutshell (possibly not complete):
* `geopaparazzispatialitelibrary` has 3 major tasks
   * read/write spatialite Databases
      * geopaparazzispatialitelibrary/src/jsqlite/Database.java
         * this is a database driver that interacts with **libjsqlite.so** defined in:
            * spatialite-android-library/jni/javasqlite-20120209/native/**sqlite_jni.c**
   * render (Paint) spatialite Geometries
      * using (the discontinued) library **vividsolutions**
         * receives geometries in the 'Well Known binary' format using:
            * `ST_AsBinary(geometry)`
   * storing Geometries connections
      * `SpatialDatabasesManager`
         * receives an Directory
            * and collects everything it can find
      * `SpatialiteDatabaseHandler`
         * receives an Spatialite-Database file
            * and stores, Table for Table, the Geometries found
      * `SpatialVectorTable`
         * store **one** Geometry column
             * with all information about the Table that contains it

---
end of part 1

**Comment by mj10777** [comment] 2015-09-03 05:16
>> Or do you have any tips on how to set up a hello world example with these libs?

Im Prinzip ja ...

---
A non *Radio Eriwan* answer would be.

Create a new Library
* indended as a Spatialite Database-Driver

Copy the `libs` of **geopaparazzispatialitelibrary**.

Copy the `src/jsqlite` of **geopaparazzispatialitelibrary**.

Study the use of 
* **jsqlite.Database**
   * `SpatialiteDatabaseHandler`

```java
private Database dbSpatialite;
dbSpatialite = new jsqlite.Database();
try 
{
 dbSpatialite.open(databasePath, jsqlite.Constants.SQLITE_OPEN_READWRITE | jsqlite.Constants.SQLITE_OPEN_CREATE);
}
```

At this point you have a connection where
* any spatial-query can be done

---
*  `DatabaseCreationAndProperties`.checkDatabaseTypeAndValidity()
   * has a **very** extensive reading logic
      * that will return all useful information found in the Database

* `DaoSpatialite`
   * has many static function that can deal with many situations

* `SPL_Vectors`
   * have many geometry specific functions

All of these can be used to study the use of **jsqlite.Database**.

---
end of part 2

**Comment by mj10777** [comment] 2015-09-03 05:22
After getting the basic `jsqlite.Database` working correctly
* try to extend it to include
   * `src/com/vividsolutions` 

which would add the functionality
* to display / Paint the geometries retrieved by `jsqlite.Database`
   * based on the code found, in the above meantioned
      * `drawFromSpatialite()`

---
Hope this helps

**Comment by mj10777** [comment] 2015-09-03 05:48
>> I am perfectly willing to take on the effort to create such a hello world example to go with these libs and make it open source of course.

This would be welcomed and I would gladly add this to the repository
* since we cooperate closely with the spatialite project
   * keeping everything up to date 
      * so having a simple project using it would be useful for anybody as a starting point

**Comment by kristina-hager** [comment] 2015-09-03 23:11
Hi Mark, 
Thanks so much for your detailed reply!

I have followed your instructions and put together a couple of GIT repositories showing progress thus far.
e.g.
[https://github.com/kristina-hager/Spatialite-Database-Driver]
[https://github.com/kristina-hager/HelloToSpatialite/tree/master]

The issue I'm having is one I've encountered repeatedly already. I have made some brute force attempts to address them without any luck yet.

Namely, I have put the jsqlite source here:
`Spatialite-Database-Driver/spatialite-db-driver/src/jsqlite` in imitation of geopaparazzi. The namespace for those files remains 'package jsqlite'.

I have set up 'HelloToSpatialite' to depend on the library 'Spatialite-Database-Driver'. That much seems to work. (It's not clear from these repos but I've used the same technique elsewhere).

However, I am having trouble using jsqlite code in: `HelloToSpatialite/app/src/main/java/pimp/hellotospatialite/GeoDatabaseHandler.java`. Specifically, I cannot find the right `import` statement for that file. I've tried `import jsqlite` of course, but that is marked an error by the Android Studio IDE. 

I have also (in other projects, not published) tried putting the jsqlite source down in the `HelloToSpatialite/app/src/main/java/pimp/` path. That seemingly helps because I can now do an `import pimp.spatialite_database_driver.jsqlite.Database` in `GeoDatabaseHandler.java` which is recognized as valid. Btw, in this case I have changed the package from `package jsqlite` to ` pimp.spatialite_database_driver.jsqlite`. However, the IDE complains about `Cannot resolve corresponding JNI function` for `private native` functions. Some searches on StackOverflow lead me to believe that this is because the namespace of the source changed.

Therefore, I feel very stuck! I don't know how geoparazzi manages to successfully declare and use the global 'jsqlite' package, or how I can convince my app and library to mimic the same.

**Comment by mj10777** [comment] 2015-09-04 12:48
I am not an expert on the android (java) projects, since they are quite different than 'normal' projects.
* Andrea does this, more so since using gradle.

As far as I remember, since a apk package must include everything it uses
* everything must be defined inside that project

So you create a new project
* (If I remember correctly) as a application project
    * then with an extra command
       * add a library to the Application project

---
This was how geopaparzzi (before gradle) was created
* `geopaprazzi` [In your case  HelloToSpatialite]
   * `geopararrazi.app` (as a directory) [In your case 'app' in HelloToSpatialite]
   * `geopaparazzispatialitelibrary` (as a directory)
   * config files for the project
      * where information is stored
         * that `geopararrazi.app` is dependent on `geopaparazzispatialitelibrary`

---
You have made 2 projects
* not 1, where the application need a extra library

This may be the cause of your problems.

**Comment by kristina-hager** [comment] 2015-09-05 21:22
Hi Mark, 
Just a quick and very happy update:

I have managed to get my Spatialite lib and app project compiling, running, and echoing out the spatialite component versions as in the tutorial!

I basically had to do some fidgeting with the library component to get the app component to recognize it.

Here's the repositories:
https://github.com/kristina-hager/Spatialite-Database-Driver
https://github.com/kristina-hager/HelloToSpatialite
with a minimal README. I will keep updating 'HelloToSpatialite' java and the README's this weekend. 

Thanks so much for your conversation and help thus far! I'm super happy to have gotten this far after fidgeting with Android Studio for hours.

**Comment by mj10777** [comment] 2015-09-06 06:48
I have quickly browsed through both projects and the results look promising.

At this point, however, I would **strongly** suggest the following
* combine the information of the two README.md files
   * together with the 'Notes' in the source code
      * as in 'src/main/AndroidManifest.xml'
   * into the wiki and reference the the wiki in the README.md

The goal should be that a
* step by step instructions should make it clear to the reader how to deal with this matter
   * photos also can be added, showing 'HelloToSpatialite' displaying some result

---
The next step would be to apply this logic to the present
* `geopaparazzispatialitelibrary`
   * calling it `spatialite_database_handler`
      * please: only lowercase
      * Andrea will hate the '_', but I prefer them, making it more readable

Here the main problem will be
* resolving the use of `eu.geopaparazzi.library`
   * I will attempt, today, to make a copy of these classes in
      * `eu.geopaparazzi.spatialite.library`

If I can get a running version, with these changes made
* I will commit this to the present branch
   * `rasterlite2_styles`

Afterwhich I will attempt to create and apply
* `SpatialiteOverlay.java`
   * committing the changes, again into
      *  `rasterlite2_styles`

At that point, to my knowledge
* `geopaparazzispatialitelibrary` should then be self contained

An attempt to create a `spatialite_database_handler` could then be made.

I assume that a major portion will be renaming the structure
* removing the `eu.geopaparazzi.` portion

Since `spatialite` (from 'eu.geopaparazzi.spatialite')
* is to general

should be renamed to
* `spatialite_handler` (the directory 'spatialite')
   * since it is **more** that a database driver

---
If you could get that working
* hellotospatialite (as used in GeoDatabaseHandler.java)
   * should work without further changes

If successful
* I would then attempt to rebuild the `geopaparazzi` project using it
   * I would have to do the same with `geopaparazzimapsforge`
      * which is completely dependent on `geopaparazzispatialitelibrary`

**Comment by kristina-hager** [comment] 2015-09-07 00:35
Hi Mark, I will take some steps to move my documentation from the readme to the wiki this week.

For today and tomorrow, I am going to look into the map rendering following the examples in `drawFromSpatialite()`. I did get a chance to check out the `rasterlite2_styles` branch of geopapparazzi.

Thanks again

**Comment by mj10777** [comment] 2015-09-08 09:51
I have just committed, what I believe to be, a workable version of
*  `geopaparazzispatialitelibrary` and
* `geopaparazzimapsforge`
   * with a (mapsforge specific) Overlay (called **GpsGeometryOverlay**)

Both of these should be completely independent of of the other libraries
* `geopaparazzimapsforge`
   * is dependent on `geopaparazzispatialitelibrary`

---
An Application wishing to use this **must** fulfill certain conditions
* the application class **must** be an extendtion of `GPApplication`
   * it must implement a `DatabaseManager`
      * that returns an Application Database storing Information such as
         * among other things: Logs,and GpsLog entries
            * see: 
               * `GeopaparazziApplication.java' 
               * `geopaparazzi.app/src/eu/hydrologis/geopaparazzi/database`
* and Application-Activity (see: `GeoPaparazziActivity.java`)
   * could start the GpsSevice logic
   * could start the MapsDirManager logic
     * see `initMapsDirManager`
* and Application-MapsActivity (see: `MapsActivity.java`)
   * can then inter act with the MapsDirManager

**Comment by mj10777** [comment] 2015-09-09 09:16
It has been decided
* to withdraw the changes made in the `rasterlite2_styles` branch
   * until a more precise decision as to what this should entail has been made

If you have made a copy in the mean time
* please do **not** make this public

---
* `spatialite_database_driver`
  * with **only** the `jsqlite` portion
      * is no problem

---
It would also be interesting to see if a 
* **spatialite_database_driver.jar**
   * can be made out of this
      * so only that needed to be included in another project

**Comment by kristina-hager** [comment] 2015-09-10 16:44
>>It has been decided to withdraw the changes made in the rasterlite2_styles branch
until a more precise decision as to what this should entail has been made

Well, it looks like I took a day off at a very unfortunate time! I was really hoping that these changes would make it easier/possible to use the very well developed code like `SpatialVectorTable.java` and it's friends.

Can I ask you to elaborate a little more on this decision and what, if any, the overall goals are on making components of geopapparazzi reusable?

And if I can help in any way? The app I am hoping to make would need a notable portion of the functionality that is already implemented in `geopaparazzispatialitelibrary`. I would far rather expend effort helping to make this component reusable than to write my own code doing similar things. After all, any code I wrote in such a short period of time would surely do much less good of a job!

**Comment by moovida** [comment] 2015-09-10 18:46
Hi @kristina-hager , I am afraid that is kind of my fault. Only kind of, since geopaparazzi was not designed to create apps out of the context it was created for. I explained everything a bit better here: https://github.com/geopaparazzi/geopaparazzi/issues/281#issuecomment-138790636

To do what you want to needs more time to make a clean split, and at the moment we do not have the resources to do that. Also I think I am the only one who knows thee complete codebase well enough to make this happen without breaking everything by introducing memory leaks and endless code duplication. Since in the past I accepted code contributions that then kept me working on fixing for days, I am now a bit more careful. 

I am not completely sure why you can't also use the geopaparazzi library as base, which has everything needed, but I had no time to read through the discussion which I am grateful Mark answered you.

**Comment by kristina-hager** [comment] 2015-09-13 14:29
Hi @moovida  and @mj10777 , 
As always, thanks so much for your responses.

I have tried to just include the geopaparazzilibrary and geopaparazzispatialitelibrary as modules in a project. I can get the project to compile, but I am having problems at runtime. The message is a bit cryptic, so it's not easily debugged (for me anyway).

I've decided to regroup a bit and do some more investigation into how to mix and match both POJO (plain old java) and Android libraries together in an Android app. I am still relatively new to Android/java development, so I hope these simple investigations may illustrate for me what is needed to set up dependency relationships between separate components.

After my 'hello world' work on modules, I will work on this:
>It would also be interesting to see if a spatialite_database_driver.jar so only that needed to be included in another project
and then make a new [HelloToSpatialite](https://github.com/kristina-hager/HelloToSpatialite) using that jar. I will check back with this thread when I get that done.

Once that is done, I may come back to the geopaparazzi code and see if I can figure out how to reuse any code in there. My app needs only a subset of geopaparazzi functionality. Specifically, I want to be able to render a map from a spatialite database source and associate that map with the users current location. Zoom and pan would also be nice features.
After some investigation into the code, helped by @mj10777, I was specifically hoping to use classes like `SpatialVectorTable` and `SpatialDatabaseHandler` (and their dependencies) from geopaparazzispatialitelibrary. My initial thought was that I'd need to make my own `SpatialDatabasesManager` for my own (much simpler) purposes.

**Comment by kristina-hager** [comment] 2015-09-25 02:30
Hi @mj10777 , 
I have finally managed to put together a jar of the spatiate android JNI libs:
https://bintray.com/kristina-hager/kh-examples/spatialite-android/1.0.0/view#files

This is an example using it:
https://github.com/kristina-hager/hello-spatialite-jar

and here is the code that builds and promotes the jar:
https://github.com/kristina-hager/spatialite-android-database-driver

I still need to clean up some hard coding in the spatialite-android/build.gradle in the last project. Also, I am quite sure the version '1.0.0' is not right. However, I wanted to get some feedback on this before getting into too much formality here. If this code works out, then I would assume the ownership of the jar build would go into this repository and not mine!

I also don't suspect this project is currently using gradle, but perhaps the gradle aspect could be integrated in anyway?

**Comment by mj10777** [comment] 2015-11-06 04:07
I am afraid, that I have completely neglected you in this matter
* for which I am sorry

**Comment by kristina-hager** [comment] 2015-11-06 20:34
Hi Mark, 
I did manage to get a basic hello world example working as I documented above. I also managed to get spatialite for android packaged into a JAR. It is far simpler, of course, for a developer to work with a JAR than to work with the individual pieces of Spatialite for Android. Additionally, using a JAR promotes reusability of this library especially as the Android IDE evolves.

Do you think you or anyone else would be interested in distributing Spatialite for Android as a JAR? 

I am not sure if you, geopaparazzi, or someone else is the owner/maintainer of Spatialite for Android / Spatialite at this point. I would also be willing to help in whatever way I can. For instance, I could work w/  the geopaparazzi repo to modify it to use the JAR and perhaps with libjsqlite to see if I can get that codebase to create a JAR. It would be ideal to distribute this JAR under the proper name/ownership at JCenter and get it properly signed and versioned.

**Comment by manishmanipal123** [comment] 2017-03-07 06:07
Hi kristina-hager
Great Work done by you as far the spatiallite jar is concerned.Really appreciate your work as it made life simpler for guys like us who have never worked on NDKs.
Thanks a Ton.

**Closed** 2018-05-08 08:43 UTC
